name: PR Validation

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false

      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cargo

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: cross

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            command: cargo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo and cross
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cross
        if: matrix.platform.command == 'cross'
        run: |
          if ! command -v cross &>/dev/null; then
            cargo install cross
          fi

      - name: Build
        run: ${{ matrix.platform.command }} build --target ${{ matrix.platform.target }}

      - name: Test
        run: ${{ matrix.platform.command }} test --target ${{ matrix.platform.target }}
