name: PR Validation

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

  build-and-test-win:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

  build-and-test-arm-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cross
        run: cargo install cross

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cross build --target aarch64-unknown-linux-gnu

      - name: Test
        run: cross test --target aarch64-unknown-linux-gnu
